version: '3.7'

services:
  # Backend API
  livi-health-app:
    container_name: livi-health-app
    build: .
    ports:
      - "8082:8182"
    restart: always
    depends_on:
      - health-status-db
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://health-status-db:3306/livi?useSSL=false&serverTimezone=UTC&useLegacyDatetimeCode=false
      SPRING_DATASOURCE_USERNAME: liviuser
      SPRING_DATASOURCE_PASSWORD: password
  # MySql DB
  health-status-db:
    container_name: health-status-db
    image: mysql:5.7
    ports:
      - "3307:3306"
    restart: always
    environment:
      MYSQL_DATABASE: livi
      MYSQL_USER: liviuser
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: password
    volumes:
      - db-data:/var/lib/mysql

# Volumes
volumes:
  db-data: